AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  smart-sales

  Sample SAM Template for smart-sales

Parameters:
  DBDriver:
    Type: String
    Description: The database driver to use (e.g., 'sqlite', 'postgresql', 'mysql', etc.)
  DBUser:
    Type: String
    Description: The database username
  DBPassword:
    Type: String
    Description: The database password
  DBHost:
    Type: String
    Description: The database host address
  DBPort:
    Type: String
    Description: The database port number
  DBName:
    Type: String
    Description: The database name
  

Globals:
  Function:
    Timeout: 20
    LoggingConfig:
      LogFormat: JSON
  Api:
    Auth:
      DefaultAuthorizer: NONE


Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,PATCH,DELETE'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
        AllowOrigin: "'*'"
  SmartSalesFunction:
    Type: AWS::Serverless::Function 
    Properties:
      MemorySize: 512
      CodeUri: .
      Handler: app.main.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Environment:
        Variables:
          DB_DRIVER: !Ref DBDriver
          DB_USER: !Ref DBUser
          DB_PASSWORD: !Ref DBPassword
          DB_HOST: !Ref DBHost
          DB_PORT: !Ref DBPort
          DB_NAME: !Ref DBName
          # AWS_REGION: ap-southeast-2
          AWS_BUCKET_NAME: smart-sales-images
      Events:
        CreateCustomer:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /customers
            Method: POST
        GetCustomer:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /customers/{customer_id}
            Method: GET
        GetAllCustomers:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /customers
            Method: GET     
        UpdateCustomer:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /customers/{customer_id}
            Method: PUT
        DeleteCustomer:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /customers/{customer_id}
            Method: DELETE
        CreateProduct:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /products
            Method: POST
        GetProduct:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /products/{product_id}
            Method: GET
        GetAllProducts:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /products
            Method: GET     
        UpdateProduct:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /products/{product_id}
            Method: PUT
        DeleteProduct:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /products/{product_id}
            Method: DELETE
        CreatePrice:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /prices
            Method: POST
        GetPrice:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /prices/{price_id}
            Method: GET
        GetAllPrices:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /prices
            Method: GET     
        UpdatePrice:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /prices/{price_id}
            Method: PUT
        DeletePrice:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /prices/{price_id}
            Method: DELETE
        CreateStatus:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /statuses
            Method: POST
        GetStatus:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /statuses/{status_id}
            Method: GET
        GetAllStatuses:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /statuses
            Method: GET     
        UpdateStatus:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /statuses/{status_id}
            Method: PUT
        DeleteStatus:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /statuses/{status_id}
            Method: DELETE
        CreateUser:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /users
            Method: POST
        GetUser:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /users/{user_id}
            Method: GET
        GetAllUsers:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /users
            Method: GET     
        UpdateUserInfo:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /users/{user_id}
            Method: PATCH
        UpdateUserPassword:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /users/{user_id}/password
            Method: PATCH
        DeleteUser:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /users/{user_id}
            Method: DELETE
        CreateOrder:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /orders
            Method: POST
        GetOrder:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /orders/{order_id}
            Method: GET
        GetAllOrders:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /orders
            Method: GET     
        UpdateOrderStatus:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /orders/{order_id}
            Method: PATCH
        DeleteOrder:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /orders/{order_id}
            Method: DELETE
        CreateUploadURL:
          Type: Api
          Properties: 
            RestApiId: !Ref MyApi
            Path: /orders/{order_id}/attachment/upload-url
            Method: POST
        CreateViewURL:
          Type: Api
          Properties: 
            RestApiId: !Ref MyApi
            Path: /orders/{order_id}/attachment/view-url
            Method: POST
        DeleteAttachment:
          Type: Api
          Properties: 
            RestApiId: !Ref MyApi
            Path: /orders/{order_id}/attachment
            Method: DELETE
        ConfirmUpload:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /orders/{order_id}/attachment
            Method: PUT
        GetItem:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /orders/{order_id}/items/{product_id}
            Method: GET
        GetAllItems:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /items
            Method: GET
        GetItemsByOrder:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /orders/{order_id}/items
            Method: GET
        UpdateItems:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /orders/{order_id}/items
            Method: PUT

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
